version: "3.9"
services:
    jwt:
        container_name: jwt-container
        build: ./
        restart: always
        ports: 
            - "5001:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
              db:
                condition: service_healthy
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: user
          POSTGRES_DB: JwtMS
        ports:
            - "6432:5432"
        volumes:
            - ./../database:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 5

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080